In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np


In [18]:
random_int_array = np.random.randint(1, 50, size=(10))
random_int_array

array([48, 40, 24, 24, 25, 43, 39, 13, 39, 33], dtype=int32)

In [19]:
np.size(random_int_array)

10

In [20]:
npArray = np.array(random_int_array)
npArray

array([48, 40, 24, 24, 25, 43, 39, 13, 39, 33], dtype=int32)

In [21]:
npArray.dtype

dtype('int32')

In [22]:
npArray.size

10

In [23]:
npArray.ndim

1

In [26]:
mat = np.random.randint(1 , 100, size=(2,5))
mat

array([[ 1, 28, 22, 56, 31],
       [61, 44, 90, 19, 26]], dtype=int32)

In [27]:
npMat = np.array(mat)
npMat

array([[ 1, 28, 22, 56, 31],
       [61, 44, 90, 19, 26]], dtype=int32)

In [28]:
npMat.shape

(2, 5)