In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,50,size=(10))
arr

array([25, 28, 16,  9, 48, 15, 48, 19, 20, 21], dtype=int32)

In [5]:
np.mean(arr)

np.float64(24.9)

In [16]:
mat1 = np.random.randint(1,100,size=(3,3))
mat2 = np.random.randint(1,100,size=(3,3))

In [17]:
mat1


array([[98, 73, 24],
       [31, 68, 34],
       [85, 17, 34]], dtype=int32)

In [18]:
mat2

array([[29, 60, 27],
       [57, 79, 82],
       [36, 56, 44]], dtype=int32)

In [19]:
mat1mat2 = mat1 + mat2

In [20]:
mat1mat2

array([[127, 133,  51],
       [ 88, 147, 116],
       [121,  73,  78]], dtype=int32)

In [21]:
np.mean(mat1mat2)

np.float64(103.77777777777777)

In [22]:
randArr =np.random.randint(1,100,size=(20))
randArr

array([67, 77, 55, 50, 55, 27, 83, 27, 80, 21, 12, 41, 98, 31, 97, 16,  2,
       12, 20, 87], dtype=int32)

In [23]:
great_then_50 = randArr[randArr > 50]

In [24]:
great_then_50

array([67, 77, 55, 55, 83, 80, 98, 97, 87], dtype=int32)

In [27]:
arr1 = np.arange(1, 11)

In [28]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
np.random.shuffle(arr1)

In [30]:
arr1

array([ 9,  8,  7,  3,  1, 10,  5,  4,  6,  2])

In [ ]:
random_elements = np.random.choice(arr)